print("--------------------------")
print("My name is Gautam Govind")
print("I am a BTech Computer Science Engineering Student")
print("I am going to give some affirmations for students who want to become briliant in studies and want to increase their memory and concentration and become topper in their field:")
print("  I am very good at gaining knowledge and making proper use of it.")
print("  I have a winner's mindset and I love accomplishing my goals. ")  
print("  I am kind and courteous to all people.")
print("  While writing answers I recall information quickly.")
print("  There is no reason for me to compare myself with others")
print("  Nothing can stop me from living the life of my dreams.")
print("  I have a very sharp mind that makes me a good student.")
print("Practice daily morning and evening and see the magic in your life")
print("Thank You so much for visiting")